version = "3.9.4"
runner.dialect = Scala36

maxColumn = 140

danglingParentheses.preset = true

rewrite.rules = [AvoidInfix, Imports, PreferCurlyFors, RedundantBraces, RedundantParens, SortModifiers]
rewrite.imports.expand = false
rewrite.imports.sort = scalastyle
rewrite.imports.contiguousGroups = no
rewrite.scala3.insertEndMarkerMinLines = 12
rewrite.scala3.removeEndMarkerMaxLines = 10
rewrite.scala3.removeOptionalBraces = true
indent.defnSite = 2

docstrings.oneline = keep
docstrings.style = SpaceAsterisk

danglingParentheses.defnSite = false
danglingParentheses.callSite = false

align.openParenCallSite = true
align.openParenDefnSite = true

assumeStandardLibraryStripMargin = true
align.stripMargin = true

docstrings.style = SpaceAsterisk
docstrings.oneline = fold
docstrings.wrap = fold
docstrings.wrapMaxColumn = 80
docstrings.blankFirstLine = fold
docstrings.forceBlankLineBefore = false

fileOverride {
  "glob:**.sbt" {
    runner.dialect = scala212source3
  }
  "glob:**/project/**.*" {
    runner.dialect = scala212source3
  }
}
