version = "3.9.4"
runner.dialect = scala3
lineEndings = unix
maxColumn = 140

indent.defnSite = 2
indent.extraBeforeOpenParenDefnSite = 2

align.stripMargin = true
align.arrowEnumeratorGenerator = true
align.openParenCallSite = true
align.openParenDefnSite = true
align.openBracketDefnSite = false

newlines.beforeOpenParenCallSite = keep
newlines.beforeOpenParenDefnSite = keep
newlines.sometimesBeforeColonInMethodReturnType = false
newlines.usingParamListModifierPrefer = before

danglingParentheses.preset = true
danglingParentheses.defnSite = false
danglingParentheses.callSite = false

assumeStandardLibraryStripMargin = true

rewrite.rules = [AvoidInfix, Imports, PreferCurlyFors, RedundantBraces, RedundantParens, SortModifiers]
rewrite.imports.expand = false
rewrite.imports.sort = scalastyle
rewrite.imports.contiguousGroups = no
rewrite.scala3.insertEndMarkerMinLines = 12
rewrite.scala3.removeEndMarkerMaxLines = 10
rewrite.scala3.removeOptionalBraces = true

docstrings.oneline = keep
docstrings.style = SpaceAsterisk
docstrings.style = SpaceAsterisk
docstrings.oneline = fold
docstrings.wrap = fold
docstrings.wrapMaxColumn = 80
docstrings.blankFirstLine = fold
docstrings.forceBlankLineBefore = false

fileOverride {
  "glob:**.sbt" {
    runner.dialect = scala212source3
    newlines.beforeOpenParenCallSite = null
  }
  "glob:**/project/**.*" {
    runner.dialect = scala212source3
    newlines.beforeOpenParenCallSite = null
  }
}
