version = "3.11.4"
runner.dialect = scala36
lineEndings = unix
maxColumn = 140

indent.defnSite = 2
indent.extraBeforeOpenParenDefnSite = 2

align.stripMargin = true
align.arrowEnumeratorGenerator = true
align.openParenCallSite = true
align.openParenDefnSite = true
align.openBracketDefnSite = false

newlines.beforeOpenParenCallSite = keep
newlines.beforeOpenParenDefnSite = keep
newlines.sometimesBeforeColonInMethodReturnType = false
newlines.usingParamListModifierPrefer = before

danglingParentheses.preset = true
danglingParentheses.defnSite = false
danglingParentheses.callSite = false

assumeStandardLibraryStripMargin = true

rewrite.rules = [AvoidInfix, PreferCurlyFors, RedundantBraces, RedundantParens, SortModifiers]
rewrite.scala3.insertEndMarkerMinLines = 12
rewrite.scala3.removeEndMarkerMaxLines = 10
rewrite.scala3.removeOptionalBraces = true

#docstrings.style = SpaceAsterisk # Retained for manual formatting use
docstrings.style = keep # Prevents header mangling. Allows CI checks to pass. Use `SpaceAsterisk` otherwise
docstrings.removeEmpty = true
docstrings.oneline = fold
docstrings.wrap = fold
docstrings.wrapMaxColumn = 80
docstrings.blankFirstLine = fold
docstrings.forceBlankLineBefore = true

fileOverride {
  "glob:**.sbt" {
    newlines.beforeOpenParenCallSite = null
  }
  "glob:**/project/**.*" {
    newlines.beforeOpenParenCallSite = null
  }
}
