import sbt.*
import com.github.tototoshi.csv.*
import _root_.io.circe.*
import _root_.io.circe.generic.auto.*
import _root_.io.circe.yaml.parser
import java.nio.charset.StandardCharsets
import java.time.Instant
import scala.collection.immutable.SortedSet
import scala.io.Source
import scala.util.{Try, Using}

object CountriesPopulator {

  private case class ParsedCountryData(name: String, alpha2: String, alpha3: String, m49: Int)
  private case class SupplementalCountry(name: String, alpha2: String, alpha3: String, m49: Int)
  private case class SupplementalRoot(countries: List[SupplementalCountry])
  private object UNSDFormat extends DefaultCSVFormat { override val delimiter: Char = ';' }

  def generate(projectRootDir: File, targetDir: File, log: Logger): (String, File) = {
    val targetFile = targetDir / "Countries.scala"
    val sourceCsvFile = projectRootDir / "countries-iso3166.csv"
    val supplementalYamlFile = projectRootDir / "supplemental-countries.yml"
    if (!sourceCsvFile.exists()) sys.error(s"CountriesPopulator: Source CSV file does not exist at: ${sourceCsvFile.getAbsolutePath}")
    implicit val countryOrdering: Ordering[ParsedCountryData] = Ordering.by(_.alpha2)
    val baseCountries = Try(Using.resource(CSVReader.open(sourceCsvFile)(UNSDFormat)) { r =>
      r.iteratorWithHeaders.zipWithIndex
        .flatMap { case (rowMap, index) => fromCsvRow(rowMap, sourceCsvFile.getName, index + 2) }
        .to[SortedSet]
    }).getOrElse(sys.error(s"Could not load or parse ${sourceCsvFile.getName}."))
    val supplementalCountries = parseYaml[SupplementalRoot](supplementalYamlFile, log).map(_.countries).getOrElse(Nil)
    val baseCountryMap = baseCountries.map(c => c.alpha2 -> c).toMap
    val supplementalMap = supplementalCountries.map(c => c.alpha2 -> ParsedCountryData(c.name, c.alpha2, c.alpha3, c.m49)).toMap
    val finalCountries = (baseCountryMap ++ supplementalMap).values.to[SortedSet]
    log.info(s"Loaded ${finalCountries.size} total unique country records.")
    val countrySource = generateCountriesFileSource(finalCountries)
    (countrySource, targetFile)
  }

  private def escapeScalaString(raw: String): String =
    if (raw == null) "null"
    else "\"" + raw.flatMap {
      case '"'  => "\\\""
      case '\\' => "\\\\"
      case '\n' => "\\n"
      case '\r' => "\\r"
      case '\t' => "\\t"
      case c    => c.toString
    } + "\""

  private def fromCsvRow(rowMap: Map[String, String], fileName: String, lineNum: Int): Option[ParsedCountryData] = {
    val name = rowMap.getOrElse("Country or Area", "").trim
    val m49Str = rowMap.getOrElse("M49 Code", "").trim
    val alpha2 = rowMap.getOrElse("ISO-alpha2 Code", "").trim.toUpperCase
    val alpha3 = rowMap.getOrElse("ISO-alpha3 Code", "").trim.toUpperCase
    if (name.isEmpty && m49Str.isEmpty && alpha2.isEmpty && alpha3.isEmpty) return None
    if (name.isEmpty) sys.error(s"Validation failed in $fileName (Line $lineNum): 'Country or Area' cannot be empty. Row: $rowMap")
    if (!alpha2.matches("^[A-Z]{2}$"))
      sys.error(s"Validation failed in $fileName (Line $lineNum): 'ISO-alpha2 Code' ('$alpha2') is not 2 uppercase letters. Row: $rowMap")
    if (!alpha3.matches("^[A-Z]{3}$"))
      sys.error(s"Validation failed in $fileName (Line $lineNum): 'ISO-alpha3 Code' ('$alpha3') is not 3 uppercase letters. Row: $rowMap")
    if (!m49Str.matches("^[0-9]+$"))
      sys.error(s"Validation failed in $fileName (Line $lineNum): 'M49 Code' ('$m49Str') is not a valid number. Row: $rowMap")
    val m49 = Try(m49Str.toInt).getOrElse(sys.error(s"Critical error parsing M49 code '$m49Str' to Int."))
    if (m49 < 1 || m49 > 999)
      sys.error(s"Validation failed in $fileName (Line $lineNum): M49 code '$m49' is out of the valid range (1-999). Row: $rowMap")
    Some(ParsedCountryData(name, alpha2, alpha3, m49))
  }
  private def parseYaml[A: Decoder](file: File, log: Logger): Option[A] = {
    if (!file.exists()) {
      log.info(s"Optional data file not found: ${file.getAbsolutePath}. Skipping.")
      return None
    }
    val yamlString = Using.resource(Source.fromFile(file, StandardCharsets.UTF_8.name()))(_.mkString)
    parser.parse(yamlString) match {
      case Left(e)     => sys.error(s"YAML parsing failed for ${file.getName}: ${e.getMessage}")
      case Right(json) =>
        json.as[A] match {
          case Left(e)     => sys.error(s"YAML decoding failed for ${file.getName}: ${e.getMessage}\n${e.history.mkString("\n")}")
          case Right(data) => Some(data)
        }
    }
  }

  private def generateCountriesFileSource(countries: SortedSet[ParsedCountryData]): String = {
    val sb = new StringBuilder()
    sb.append(s"""// DO NOT EDIT - FILE AUTOMATICALLY GENERATED BY `CountriesPopulator.scala` at ${Instant.now}.
package world.locale.country

import world.locale.errors.{DuplicateCountryData, LocaleError}

/** A sealed trait representing a country or area with its primary identifiers. */
sealed trait Country extends Product with Serializable derives CanEqual:
  val name: String
  val alpha2: Alpha2Code
  val alpha3: Alpha3Code
  val m49: M49Code

/** A concrete representation for a country that is not one of the predefined singletons. */
private[country] final case class GenericCountry(
    name: String,
    alpha2: Alpha2Code,
    alpha3: Alpha3Code,
    m49: M49Code)
    extends Country

/** Provides a factory for creating custom `Country` instances. */
object Country:
  /** The default `given` instance for the set of countries used for validation.
    * By default, this is the complete set of predefined countries from the [[Countries]] object.
    */
  given Set[Country] = Countries.all

  /** Creates a custom `Country` instance if the provided data is valid and does not
    * conflict with any of the countries in the contextual `existingCountries` set.
    *
    * @param existingCountries The set of countries to check for duplicates against.
    * A default is provided, but users can supply their own `given Set[Country]` to
    * validate against a custom universe of countries.
    * @return A `Right` containing a new [[GenericCountry]], or a `Left` with a [[world.locale.errors.LocaleError]].
    */
  def generic(
      name: String,
      alpha2: String,
      alpha3: String,
      m49: Int
  )(using Set[Country]): Either[LocaleError, Country] =
    def unique[A](label: String, value: A)(predicate: Country => Boolean): Either[LocaleError, Unit] =
      Either.cond(!summon[Set[Country]].exists(predicate), (), DuplicateCountryData(s"$$label '$${value.toString}' is already in use."))
    for
      a2   <- Alpha2Code.from(alpha2)
      a3   <- Alpha3Code.from(alpha3)
      m49c <- M49Code.from(m49)
      _    <- unique("Alpha-2 code", a2)(_.alpha2 == a2)
      _    <- unique("Alpha-3 code", a3)(_.alpha3 == a3)
      _    <- unique("M49 code", m49c)(_.m49 == m49c)
    yield GenericCountry(name, a2, a3, m49c)

/** Provides predefined singleton instances for all countries/areas and lookup methods.
  * @note This file is automatically generated. Data sourced from UNSD.
  */
object Countries:

""")

    countries.foreach { c =>
      val objectName = c.alpha2
      val escapedNameLiteral = escapeScalaString(c.name)
      sb.append(s"""  /** A singleton instance of [[Country]] for '''${c.name.trim}'''. */
  case object $objectName extends Country:
    val name: String = $escapedNameLiteral
    val alpha2: Alpha2Code = Alpha2Code.unsafeFrom("${c.alpha2}")
    val alpha3: Alpha3Code = Alpha3Code.unsafeFrom("${c.alpha3}")
    val m49: M49Code = M49Code.unsafeFrom(${c.m49})

""")
    }

    val countrySetElements = countries.map(_.alpha2).mkString(",\n    ")
    sb.append(
      s"""  /** A `Set` containing all defined [[Country]] instances in this object. */
  val all: Set[Country] = Set(\n    $countrySetElements\n  )\n\n""" +
        s"""  import scala.annotation.targetName

  def from(code: Alpha2Code)(using Set[Country]): Option[Country] = summon[Set[Country]].find(_.alpha2 == code)
  @targetName("fromAlpha3Code") def from(code: Alpha3Code)(using Set[Country]): Option[Country] = summon[Set[Country]].find(_.alpha3 == code)
  @targetName("fromM49Code") def from(code: M49Code)(using Set[Country]): Option[Country] = summon[Set[Country]].find(_.m49 == code)
  @targetName("fromCountryName") def from(name: String)(using Set[Country]): Option[Country] = summon[Set[Country]].find(_.name.equalsIgnoreCase(name.trim))

  def fromAlpha2(code: String): Option[Country] = byAlpha2.get(code.trim.toUpperCase.nn)
  def fromAlpha3(code: String): Option[Country] = byAlpha3.get(code.trim.toUpperCase.nn)
  def fromM49(code: Int): Option[Country] = byM49.get(code)
  def fromName(name: String): Option[Country] = byName.get(name.trim.toLowerCase.nn)
  def apply(identifier: String): Option[Country] =
    val trimmed = identifier.trim.nn
    if trimmed.length == 2 then fromAlpha2(trimmed)
    else if trimmed.length == 3 then fromAlpha3(trimmed)
    else fromName(trimmed)
  def apply(identifier: Int): Option[Country] = fromM49(identifier)

  private lazy val byAlpha2: Map[String, Country] = all.map(c => c.alpha2.value -> c).toMap
  private lazy val byAlpha3: Map[String, Country] = all.map(c => c.alpha3.value -> c).toMap
  private lazy val byM49: Map[Int, Country] = all.map(c => c.m49.value -> c).toMap
  private lazy val byName: Map[String, Country] = all.map(c => c.name.toLowerCase -> c).toMap

end Countries
""")
    sb.toString()
  }
}
