addSbtPlugin("africa.shuwari" % "sbt-version" % "0.8.0")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.9.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.1")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.3.1")
addSbtPlugin("africa.shuwari.sbt" % "sbt-shuwari" % "0.15.4")
// addSbtPlugin("africa.shuwari.sbt" % "sbt-shuwari-js" % "0.15.4")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.7")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.22.0")
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.5.12")
addSbtPlugin("com.github.sbt" % "sbt-unidoc" % "0.6.1")
